#!/usr/bin/env bash
set -eu

ENV_FILE=".env"

prompt() {
  printf "%s" "$1"
  read -r answer
  printf "%s" "$answer"
}

require_value() {
  value="$1"
  name="$2"
  if [ -z "$value" ]; then
    echo "Error: $name is required." >&2
    exit 1
  fi
}

echo "Welcome to ChatBizOS setup."
echo "This wizard creates a .env file for your local deployment."
echo

LLM_PROVIDER=$(prompt "Choose LLM provider (openai/anthropic/local): ")
case "$LLM_PROVIDER" in
  openai|anthropic|local) ;;
  *) echo "Unsupported LLM provider: $LLM_PROVIDER" >&2; exit 1 ;;
esac

OPENAI_API_KEY=""
ANTHROPIC_API_KEY=""
LOCAL_LLM_ENDPOINT="http://localhost:11434"

case "$LLM_PROVIDER" in
  openai)
    OPENAI_API_KEY=$(prompt "Enter OpenAI API key: ")
    require_value "$OPENAI_API_KEY" "OPENAI_API_KEY"
    ;;
  anthropic)
    ANTHROPIC_API_KEY=$(prompt "Enter Anthropic API key: ")
    require_value "$ANTHROPIC_API_KEY" "ANTHROPIC_API_KEY"
    ;;
  local)
    LOCAL_LLM_ENDPOINT=$(prompt "Enter local LLM endpoint [http://localhost:11434]: ")
    if [ -z "$LOCAL_LLM_ENDPOINT" ]; then
      LOCAL_LLM_ENDPOINT="http://localhost:11434"
    fi
    ;;
esac

echo
CHAT_CHANNEL=$(prompt "Choose chat channel (discord/slack): ")
case "$CHAT_CHANNEL" in
  discord|slack) ;;
  *) echo "Unsupported chat channel: $CHAT_CHANNEL" >&2; exit 1 ;;
esac

DISCORD_BOT_TOKEN=""
DISCORD_GUILD_ID=""
DISCORD_CHANNEL_ID=""
SLACK_BOT_TOKEN=""
SLACK_APP_TOKEN=""
SLACK_CHANNEL_ID=""

case "$CHAT_CHANNEL" in
  discord)
    DISCORD_BOT_TOKEN=$(prompt "Enter Discord bot token: ")
    DISCORD_GUILD_ID=$(prompt "Enter Discord guild ID: ")
    DISCORD_CHANNEL_ID=$(prompt "Enter Discord channel ID: ")
    require_value "$DISCORD_BOT_TOKEN" "DISCORD_BOT_TOKEN"
    require_value "$DISCORD_GUILD_ID" "DISCORD_GUILD_ID"
    require_value "$DISCORD_CHANNEL_ID" "DISCORD_CHANNEL_ID"
    ;;
  slack)
    SLACK_BOT_TOKEN=$(prompt "Enter Slack bot token: ")
    SLACK_APP_TOKEN=$(prompt "Enter Slack app token: ")
    SLACK_CHANNEL_ID=$(prompt "Enter Slack channel ID: ")
    require_value "$SLACK_BOT_TOKEN" "SLACK_BOT_TOKEN"
    require_value "$SLACK_APP_TOKEN" "SLACK_APP_TOKEN"
    require_value "$SLACK_CHANNEL_ID" "SLACK_CHANNEL_ID"
    ;;
esac

echo
TIMEZONE=$(prompt "Enter timezone [UTC]: ")
if [ -z "$TIMEZONE" ]; then
  TIMEZONE="UTC"
fi

OPENCLAW_GATEWAY_TOKEN="$(
  node -e "process.stdout.write(require('node:crypto').randomBytes(24).toString('hex'))"
)"

cat > "$ENV_FILE" <<EOF
# Generated by ChatBizOS setup.sh
LLM_PROVIDER=$LLM_PROVIDER
OPENAI_API_KEY=$OPENAI_API_KEY
ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY
LOCAL_LLM_ENDPOINT=$LOCAL_LLM_ENDPOINT
CHAT_CHANNEL=$CHAT_CHANNEL
DISCORD_BOT_TOKEN=$DISCORD_BOT_TOKEN
DISCORD_GUILD_ID=$DISCORD_GUILD_ID
DISCORD_CHANNEL_ID=$DISCORD_CHANNEL_ID
SLACK_BOT_TOKEN=$SLACK_BOT_TOKEN
SLACK_APP_TOKEN=$SLACK_APP_TOKEN
SLACK_CHANNEL_ID=$SLACK_CHANNEL_ID
OPENCLAW_PORT=18789
OPENCLAW_GATEWAY_TOKEN=$OPENCLAW_GATEWAY_TOKEN
TIMEZONE=$TIMEZONE
EOF

if [ ! -s "$ENV_FILE" ]; then
  echo "Failed to write $ENV_FILE" >&2
  exit 1
fi

echo
echo "Configuration written to $ENV_FILE"
echo "Validation checks:"
echo "- LLM provider: $LLM_PROVIDER"
echo "- Chat channel: $CHAT_CHANNEL"
echo "- Timezone: $TIMEZONE"
echo
echo "Next steps:"
echo "1. Review $ENV_FILE"
echo "2. Run: docker compose up -d"
echo "3. Run: ./setup/register-cron.sh"
echo "4. Run: ./setup/validate.sh"
